branding = float(input("Enter branding expenses\n"))
travel = float(input("Enter travel expenses\n"))
food = float(input("Enter food expenses\n"))
logostic = float(input("Enter logistics expenses\n"))
total = ((branding + travel + food + logostic ))
bp = "{0: .2f}".format((branding / total * 100))
tp = "{0: .2f}".format((travel / total * 100))
fp = "{0: .2f}".format((food / total * 100))
lp = "{0: .2f}".format((logostic / total * 100))  
total = "{0: .2f}". format(total)

print("Total expenses : Rs." + str(total))
print("Branding expenses percentage : " +  str(bp )+ "%")
print("Travel expenses percentage : " + str(tp) + "%")
print("Food expenses percentage : " + str(fp) + "%")
print("Logistics expenses percentage : " + str(lp) + "%")